### ISSUE TITLE
Some typos in the recent SSL/TLS chapter

### ISSUE THREAD

**Issue by TheForcer** [ghandmann/HS-AlbSig-WebAnwendungen2#1]
In most slides:
Asymetrisch --> Asymmetrisch
Symetrisch --> Symmetrisch

Folie 09 --> "Verschlüsselung der Kommunikation"
Folie 14 --> "Informationen zum Public Key"
Folie 14 --> "Zusätze"
Folie 15 --> "vertrauenswürdige"
Folie 17 --> "Extended"
Folie 19 --> "zustande"

**Comment by ghandmann** [comment]
Thanks for the corrections! :)
