### ISSUE TITLE
Fehlende Klammer beim Code Beispiel zu Promises

### ISSUE THREAD

**Issue by MaxAtoms** [ghandmann/HS-AlbSig-WebAnwendungen2#10]
@mrc30 ist gestern aufgefallen, dass auf Folie 12 in [Kapitel/05_Web2.0_AJAX_1x1.odp](https://github.com/ghandmann/HS-AlbSig-WebAnwendungen2/blob/aa671ea/Kapitel/05_Web2.0_AJAX_1x1.odp) am Ende der Zeile eine Klammer fehlt:
```
promise.done(() => console.log("Fertig");
```

**Comment by ghandmann** [comment]
@MaxAtoms  und @mrc30:
Danke für den Hinweis! :)
